AWSTemplateFormatVersion: '2010-09-09'
Description: 'Full Stack Application CloudFormation Template'

Resources:
  CloudFormationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'fullstackapp-cf-bucket'
      websiteConfiguration:
        indexDocument: index.html
        errorDocument: error.html

Outputs:
  WebsiteURL:
    Value:  'CloudFormationBucket.WebsiteURL'
    Description: URL of the S3 static website
  S3BucketSecureURL:
    Value:  'CloudFormationBucket.DomainName'
    Description: Secure URL of the S3 bucket