AWSTemplateFormatVersion: '2010-09-09'
Description: 'Full Stack Application CloudFormation Template'

Resources:
  CloudFormationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'fullstackapp-${EnvironmentName}-cf-bucket'
      websiteConfiguration:
        indexDocument: index.html
        errorDocument: error.html

Outputs:
  websiteURL:
    Value:  'http://${CloudFormationBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Description: URL of the S3 static website
  s3BucketSecureURL:
    Value:  'https://${CloudFormationBucket}.s3.amazonaws.com'
    Description: Secure URL of the S3 bucket